### ISSUE TITLE
can you give a video about how to insall it?

### ISSUE THREAD

**Issue by wiatingpub** [rohitgandikota/erasing#11]

**Comment by rohitgandikota** [comment]
Hey, did you try the installation guide? I can make it more elaborate
1. clone this repository (https://github.com/CompVis/stable-diffusion)
2. `cd stable-diffusion`
3. Download the files from this repository (there will be `ldm` folder already, replace it with our version) 
4. Download the weights from (https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4-full-ema.ckpt) and move them to `stable-diffusion/models/ldm/` (This will be `ckpt_path` variable in `train-scripts/train-esd.py`)
5. To convert your trained models to diffusers download the diffusers Unet config from (https://huggingface.co/CompVis/stable-diffusion-v1-4/blob/main/unet/config.json)  (This will be `diffusers_config_path` variable in `train-scripts/train-esd.py`)
6. make sure you are in the main directory (`stable-diffusion`)
7. To train the model use: `python train-scripts/train-esd.py --prompt 'your prompt' --train_method 'your choice of training' --devices '0,1'`
