### ISSUE TITLE
ESD erases concepts beyond those being specified

### ISSUE THREAD

**Issue by ajrheng** [rohitgandikota/erasing#13]
EDIT: Celebrity erasure seems to work better with xattn. Some of the pictures of Tom Cruise would look like him, but other images would still not have him inside.

Hi, thanks for the interesting work.

I tried using ESD to erase "brad pitt" **only** (both 'full' and 'noxattn'), but found that other celebrities were also being erased. For instance, here's some samples from the prompt "a picture of tom cruise" from the noxattn model (results are similar for 'full')

![0_0](https://user-images.githubusercontent.com/34501199/236983326-49076e2e-d1a4-49e8-a301-4a255c8fb8df.png)
![0_1](https://user-images.githubusercontent.com/34501199/236983334-539b8003-d154-4a1d-b871-aa6de6f95256.png)

Compare this to the original SD v1.4 with the same prompt and seed
![00003](https://user-images.githubusercontent.com/34501199/236983386-7d4576fd-c03d-49bf-8833-7d4706b905a4.png)
![00004](https://user-images.githubusercontent.com/34501199/236983389-bbab825d-47fe-4955-be46-a049ab91b8b7.png)

Any idea why this is the case? All other hyperparameters were kept default as in `train-scripts/train-esd.py`. If it matters, I used the saved diffusers checkpoint with `eval-scripts/generate-images.py` as that seemed to work.

**Comment by rohitgandikota** [comment]
Hey thanks for sharing this cool application. You are correct, we also mention this undesired interference in our work. For a more targeted erasures, I would suggest "xattn" training. But it seems like from your experiments that seems to be the case. 

"xattn" model after removing brad Pitt:

<img width="815" alt="image" src="https://github.com/rohitgandikota/erasing/assets/17539718/58e18181-9290-4447-91b5-97d55a1a51e3">

<img width="814" alt="image" src="https://github.com/rohitgandikota/erasing/assets/17539718/77856c30-3868-48ba-a740-ad80e62ab3f6">
