### ISSUE TITLE
Doubt regarding NSFW content removal.

### ISSUE THREAD

**Issue by thakral-kartik** [rohitgandikota/erasing#16]
Hi, I find your work very interesting. I have one doubt though, for nudity removal do you start with stable diffusion model with nsfw check enabled?

**Comment by rohitgandikota** [comment]
As long as you are working in latent space, nsfw check will not come into play. So in our case, during training, we work in latent space only. So it should not affect the process.

**Comment by rohitgandikota** [comment]
To test the performance however, we do disable it and then do the  before and after-edit analysis in our paper.

**Comment by thakral-kartik** [comment]
Thanks for helping out!
