### ISSUE TITLE
Doubt Regarding Self-Attention Visualization

### ISSUE THREAD

**Issue by thakral-kartik** [rohitgandikota/erasing#17]
Hi, thanking you again for the great work!

I noticed in the paper that you gave an analysis of the below figure. While reading that, I had a doubt regarding the self-attention visualization shown in the same. For visualization (b) with prompt  "", did you give some prompt that didn’t contain “car” to generate a car image or just an empty prompt? If it was an empty prompt, how were you able to generate a similar car image as in with the prompt “car”?

<img width="415" alt="attentions" src="https://github.com/rohitgandikota/erasing/assets/20669200/c445d12c-4c7d-4c0c-af3c-dd5645a77ff2">

**Comment by rohitgandikota** [comment]
Using the prompt  "", we generated a ton of images with different seeds and looked for the ones with cars in them. After we chose a seed for "", we used the same seed and generated an image with the prompt "car".

**Comment by thakral-kartik** [comment]
Oh! That makes a lot of sense. Thanks for the prompt response.
