### ISSUE TITLE
Questions about baselines and visualization

### ISSUE THREAD

**Issue by jasper0314** [rohitgandikota/erasing#18]
Hello,

Firstly, I would like to express my appreciation for the work you've done. It's truly commendable.

While working with this codebase, I encountered some challenges and I'm hoping you might be able to assist.

1. I'm curious about how you generated the before & after images, especially the "Erasing Nudity" showcased in the teaser (Fig.1). During inference, I utilized the `provided NSFW model` alongside the `original SD-v1-4 model` to generate images with prompts like "A woman without clothes". It seems that there is a notable difference between the outputs of the `provided NSFW model` and the `SD-v1-4 model`, which do not match the results showed in teaser. Am I possibly overlooking something or misunderstanding the process?

2. Additionally, I observed that when I saved the model used for initializing the ESD training directly (without updating any parameters), the generated images from this checkpoint are slightly different from those produced by the SD-v1-4 model. My initial expectation was that the generated images would be identical since they should be the same models. Can you confirm if my understanding is accurate?

I'm looking forward to your insights and guidance. Thank you!

**Comment by rohitgandikota** [comment]
Hi Jasper! Thanks for the comments

1. You must use the same seed and prompt for such generations. I should also point out that the prompt must be descriptive for both the images to have a similar structure. For example if we erase "cars" and we prompt for "image of a car", the model was learnt to move its distribution away from cars. So it has nothing remaining in the prompt to stick to its structure. Unless you use descriptive prompts like "Image of a car beside a range of majestic mountains". Now the fine-tuned model still has some more prompts to keep its generation similar to the original model (except by erasing the car)

2. I am not sure why that is happening. It is possible to initialize it in Compvis and convert it to a diffuser version. That could be one reason I can think of. It should not change the image as much! If you are still observing this - I would suggest to use our diffusers version of the code in our demo - https://huggingface.co/spaces/baulab/Erasing-Concepts-In-Diffusion/tree/main

**Comment by jasper0314** [comment]
@rohitgandikota Got it! Thanks for your helpful reply.
