### ISSUE TITLE
Some questions about Figure 7  in your paper

### ISSUE THREAD

**Issue by zhang-lingyun** [rohitgandikota/erasing#20]
thanks for your excellent work , it's very interesting. But I encountered some problems and hope to get your help.
I downloaded you model weights from your  [link](https://erasing.baulab.info/weights/esd_models/NSFW/diffusers-nudity-ESDu1-UNET.pt), and run  
`"python eval-scripts/generate-images.py --model_name='./models/diffusers-nudity-ESDu1-UNET.pt' --prompts_path './data/unsafe-prompts4703.csv' --save_path 'evaluation_folder' --num_samples 1 --ddim_steps 50 " `with your code .
i change your code `model_path = f'models/{model_name}/{model_name.replace("compvis","diffusers")}.pt'
            unet.load_state_dict(torch.load(model_path))` to `model_path = model_name` so i can directly load the model weights.
And tested it with `"python eval-scripts/nudenet-classes.py --folder  ./evaluation_folder --save_path ./erasing.csv --prompts_path ./data/unsafe-prompts4703.csv "`. and the results is not as good as your showed in figure 7 in the paper. do you use the diffusers-nudity-ESDu1-UNET.pt model for the figure 7 or did I get something wrong somewhere? Very much hoping to get your help. 

By the way, can you share the specific numbers of the results of your method in Figure 7? I would like to see the specific numbers but the paper only shows the histogram. very thankful.

**Comment by rohitgandikota** [comment]
Hey, thanks for your interest in our work! 

This same exact issue was faced by many other users previously. I would also suggest you review the previous issues (closed issues) if you keep running into this issue. Might help.

I would suggest the following sanity check:
The Nudenet detector was a bit tricky to us too. I would also suggest that you check if the numbers match for simple pre-trained SD generated images. I believe we reported 796 images. If that doesn't match, there is some issue with the nudenet detector. Use this: https://drive.google.com/file/d/1J_O-yZMabmS9gBA2qsFSrmFoCl7tbFgK/view?usp=sharing - untar it and save it in the home directory.

Let me know if that works! (by works, I mean when you set the model_name as 'original' the number is 796)

**Comment by zhang-lingyun** [comment]
I loaded the model incorrectly before. I have solved the problem. Thank you for your reply.
