### ISSUE TITLE
Table 2 Question

### ISSUE THREAD

**Issue by MLAlex1** [rohitgandikota/erasing#26]
Hi,

thanks for this cool work! I am a bit confused about table 2 , how do you evaluate exactly the "Accuracy of other
classes"? Do you generate 1 image per class of the 1000 classes of ImageNet or only of the classes in the table and then classify with ResNet?

Thanks!

**Comment by rohitgandikota** [comment]
Hi! We work on Imagenette (which is a subset of imagenet). The classes are shown in table2. As we described in the paper, we generate 500 images per class and then classify using resnet.

**Comment by shaswati1** [comment]
Hi,
What did you use as a guidance concept for each class in imagenette? Could you provide the list?
