### ISSUE TITLE
Info missing in the installtion guide?

### ISSUE THREAD

**Issue by xjtupanda** [rohitgandikota/erasing#5]
Thanks for the inspiring work! I'm trying to reproduce the results, and following the installation guide I find that there is no link to the iccv-esd repository nor the link to the weights. Could you please provide them?

As I quote from [here:](https://github.com/rohitgandikota/erasing#installation-guide)
> Then download the files **from our iccv-esd repository** to stable-diffusion main directory of stable diffusion. This would replace the ldm folder of the original repo with our custom ldm directory
> **Download the weights from here** and move them to stable-diffusion/models/ldm/ (This will be ckpt_path variable in train-scripts/train-esd.py)

**Comment by rohitgandikota** [comment]
Thanks for catching that! 

We mean the current repository (https://github.com/rohitgandikota/erasing). Download all the files from here to the stable-diffusion folder from CompVis. 

For the pre-trained SD-v1.4 weights. Here is the link: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4-full-ema.ckpt

**Comment by xjtupanda** [comment]
> Thanks for catching that!
> 
> We mean the current repository (https://github.com/rohitgandikota/erasing). Download all the files from here to the `stable-diffusion` folder (you would get this folder by installing the original compvis code: https://github.com/CompVis/stable-diffusion)
> 
> For the pre-trained SD-v1.4 weights. Here is the link: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4-full-ema.ckpt
> 
> We also released our fine-tuned models here: https://erasing.baulab.info/weights/esd_models/

Oh, I see. Thank you so much!
